### ISSUE TITLE
Separator line shouldn’t be below last class

### ISSUE THREAD

**Issue by jackwherry** [eado/gradeology#1]
![CE6A585C-C06B-4047-9553-560C0D3865AF](https://user-images.githubusercontent.com/17338790/72088433-c69cb800-32cf-11ea-8d1d-2e626d22b945.jpeg)

Line shouldn’t be there.

**Comment by eado** [comment]
This is probably going to be the last thing I fix.

**Comment by eado** [comment]
Fixed in last release.
